version: '3'
services:
  tassone-tv:
    build: .
    container_name: tassone-tv
    volumes:
      - ./media:/app/media
      - ./channels.json:/app/channels.json
      - ./state.json:/app/state.json
    environment:
      - PYTHONUNBUFFERED=1

      - FLASK_APP=flask_app.py
      - FLASK_DEBUG=${FLASK_DEBUG:-True}
      - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
      - FLASK_PORT=${FLASK_PORT:-5000}    
      - SECRET_KEY=${SECRET_KEY:-mysecretkey}
    ports:
      - "8059:${FLASK_PORT}"
    restart: unless-stopped
    build: .
    pull_policy: build
