version: '3'
services:
  tassone-tv:
    container_name: tassone-tv
    volumes:
      - ./media:/app/media
    environment:
      - PYTHONUNBUFFERED=1

      - FLASK_APP=flask_app.py
      - FLASK_DEBUG_OPTION=${FLASK_DEBUG_OPTION:-True}
      - FLASK_RELOADER_OPTION=${FLASK_RELOADER_OPTION:-False}
      - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
      - FLASK_PORT=${FLASK_PORT:-5000}    
      - SECRET_KEY=${SECRET_KEY:-mysecretkey}

      - MEDIA_DIR_NAME=${MEDIA_DIR_NAME:-placeholder}
      - STATE_FILE_NAME=${STATE_FILE_NAME:-placeholder}
      - CHANNELS_FILE_NAME=${CHANNELS_FILE_NAME:-placeholder}   

      - DASHBOARD_HOSTNAME=${DASHBOARD_HOSTNAME:-placeholder}   
    ports:
      - "8059:${FLASK_PORT}"
    restart: unless-stopped
    build: .
    pull_policy: build
